spring.application.name=aml-diploma-project
server.port=7777
############# DATABASE CONNECTION UCHUN ###################################
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/aml
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update

# Screening threshold (0.0 - 1.0)
screening.threshold=0.80